# Site settings
baseURL = "https://conquer.guru"
languageCode = "en-us"
title = "conquer.guru"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Your name"
  description = "Your description"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Conquer.Guru"
 ##   subtitle = "By HTML5 Up"
    menu = "Our Services"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Software Development"
      url = "blogs/aliquam"

    [[params.navigation.links]]
      name = "Coaching for students"
      url = "blogs/tempus"

    [[params.navigation.links]]
       name = "Software Consultancy"
       url = "blogs/magna"

    [[params.navigation.links]]
      name = "virtual employees"
      url = "blogs/ipsum"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    ##[[params.navigation.button1]]
    ##  name = "Our Services"
    ##  url = "blogs"

    # Button Style 2
    ##[[params.navigation.button2]]
    ##  name = "Log In"
    ##  url = "#contact"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "welcome to Conquer.Guru"
    subtitle = "We design and build smart, Artificial intelligence (AI) enabled, cloud-first business software applications."
    buttonText = "What we do?"
    url = "blogs"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Software Development"
      subtitle = "We help you to get your idea to a full fledged application."
      image = "banner1.jpg"
      url = "blogs/aliquam"

    [[params.tiles.showcase]]
      title = "Coaching for students"
      subtitle = "Launch your tech career, we will teach you the most important technical skills that are in-demand in the market today such as Serverless Architecture, React JS, Python, C#, Java, Power BI, and Selenium automation"
      image = "coaching.jpg"
      url = "blogs/tempus"

    [[params.tiles.showcase]]
      title = "Software Consultancy"
      subtitle = "Turn ideas to Great products"
      image = "Software Consultancy.png"
      url = "blogs/magna"

    [[params.tiles.showcase]]
      title = "virtual employees"
      subtitle = "If you are looking for global exposure, Virtual Employee is the right place for you."
      image = "virtualemployees.jpg"
      url = "blogs/ipsum"

   ## [[params.tiles.showcase]]
   ##   title = "Consequat"
   ##   subtitle = "Ipsum Dolor Sit Amet"
   ##   image = "pic05.jpg"
   ##   url = "blogs/ipsum"

   ## [[params.tiles.showcase]]
   ##   title = "Etiam"
   ##   subtitle = "Feugiat Amet Tempus"
   ##   image = "pic06.jpg"
   ##   url = "blogs/ipsum"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "How can we help you ?"
    subtitle = """We scope, plan, and develop custom software solutions for public, private, and non-profit organisations. We help to gain efficiencies, and competitive advantage through the smart use of technology."""
    buttonText = "Our Services"
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "guru@conquer.guru"

    [[params.contact.phone]]
    title = "Phone"
    phone = "91 7356545333, +91 4844876028"

    [[params.contact.address]]
    title = "Address"
    street = "61/492, Chiramel building, Sreekandath Road"
    city = "Cochin, Ernakulam"
    country = "Kerala, 682016"

  # Footer section
  [params.footer]
    enable = true
    copyright = "conquer.guru"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://twitter.com/ConquerGuru"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/Conquer-Guru-617620828737728/?ref=br_rs"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/conquerguru/"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://github.com/conquerguru"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/company/conquerdream/"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "our partner: "
      url= "http://conquerdream.com/"
      alt = "conquerdream.com"
